# Generated by Django 4.2.5 on 2023-10-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_options_user_date_joined_user_email_and_more'),
        ('Users', '0003_alter_user_managers'),
    ]

    operations = [
    ]
